### PR TITLE
use display-legacy from armv6

### PR DESCRIPTION
**Pull request by Kirmaniarslan**

### CODE REVIEW

**Comment by high1** [comment]
Did you not have a lot of errors in logcat when you built from this source? If we have properly working display, should we not first focus on wifi?

**Comment by Kirmaniarslan** [comment]
i thought that were due to  display changes but you are right its ok we should leave it for now

**Comment by high1** [comment]
I think that we should leave this until ION is finished - then we will upgrade drivers and repos. This works - for now.

**Comment by Kirmaniarslan** [comment]
Ok

**Pull request closed without merging**
